name: CI
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: {}
env:
  NIX_ABORT_ON_WARN: 1
jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - &install-nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix flake check --all-systems
  generate-build-matrix:
    name: generate a build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - *checkout
      - *install-nix
      - id: generate
        run: |
          matrix=$(nix eval --json .#ci.matrix)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
  build:
    name: build ${{ matrix.system }}.${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    needs: generate-build-matrix
    strategy:
      matrix: ${{ fromJSON(needs.generate-build-matrix.outputs.matrix) }}
    steps:
      - *checkout
      - *install-nix
      - run: nix build --print-build-logs .#"$attrPath"
        env:
          attrPath: ${{ matrix.attrPath }}
